### ISSUE TITLE
LoadBalancer latency always shows as "0"

### ISSUE THREAD

**Issue by chandraprakash1392** [awslabs/k8s-cloudwatch-adapter#10]
## My external-metrics adapter looks like this:
```
queries:
      - id: latency
        metricLabels: "latency"
        metricStat:
          metric:
            namespace: "AWS/ELB"
            metricName: "Latency"
            dimensions:
              - name: LoadBalancerName
                value: "ab2cc236ed3a211e98a7c122360628b8"
          period: 60
          stat: Sum
          unit: Milliseconds
        returnData: true
```

When I am running the query to fetch data from external-metrics-api inside my kubernetes cluster I get the following response:
```
{
  "kind": "ExternalMetricValueList",
  "apiVersion": "external.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/external.metrics.k8s.io/v1beta1/namespaces/chandra/elb-latency"
  },
  "items": [
    {
      "metricName": "elb-latency",
      "metricLabels": null,
      "timestamp": "2019-09-23T12:17:19Z",
      "value": "0"
    }
  ]
}
```

Whereas in cloudwatch, the datapoint is never 0
