### ISSUE TITLE
AWS ELB name

### ISSUE THREAD

**Issue by dsumsky** [awslabs/k8s-cloudwatch-adapter#17]
Let's have a k8s service of `LoadBalancer` type running on k8s cluster on AWS. It's name can be `my-nginx`. Now, I would like to define an external metric based on some of the load balancer CloudWatch metrics, e.g. `SurgeQueueLength`, `RequestCount` etc. In order to get this working I need to hardcode the load balancer name in the resource configuration:
```
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: elb-my-nginx-requests
spec:
  name: elb-my-nginx-requests
  resource:
    resource: "deployment"
  queries:
    - id: elb_my_nginx_requests
      metricStat:
        metric:
          namespace: "AWS/ELB"
          metricName: "RequestCount"
          dimensions:
            - name: LoadBalancerName
              value: "xyzxyzxyzxyz"
        period: 60
        stat: Sum
        unit: Count
      returnData: true
```

k8s service:
```
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP                                                               PORT(S)        AGE
my-nginx     LoadBalancer   10.100.32.68   xyzxyzxyzxyz.us-west-2.elb.amazonaws.com   80:30099/TCP   85m
```

Would it be possible to get the name dynamically from the service itself?
