### ISSUE TITLE
Can the adapter work with EKS Fargate type ?

### ISSUE THREAD

**Issue by rubashanti** [awslabs/k8s-cloudwatch-adapter#21]
I can see that the adapter using metadata to retrieve the region, I tried using the adapter with EKS FARGATE type cluster and I got this error :

 get hpa sqs-consumer-scaler -o yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2020-01-27T23:43:40Z","reason":"SucceededGetScale","message":"the
      HPA controller was able to get the target''s current scale"},{"type":"ScalingActive","status":"False","lastTransitionTime":"2020-01-27T23:43:40Z","reason":"FailedGetExternalMetric","message":"the
      HPA was unable to compute the replica count: unable to get external metric default/sqs-helloworld-length/nil:
      unable to fetch metrics from external metrics API: MissingRegion: could not
      find region configuration"}]'

how can we add specific region ?

is there anything else I can do to make it work with fargate cluster

**Comment by chankh** [comment]
Try adding the environment variable `AWS_REGION` to the deployment

**Comment by rubashanti** [comment]
Can you help with this error :   

  autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2020-01-28T00:06:41Z","reason":"SucceededGetScale","message":"the
      HPA controller was able to get the target''s current scale"},{"type":"ScalingActive","status":"False","lastTransitionTime":"2020-01-28T00:23:06Z","reason":"FailedGetExternalMetric","message":"the
      HPA was unable to compute the replica count: unable to get external metric default/sqs-helloworld-length/nil:
      unable to fetch metrics from external metrics API: the server is currently unable
      to handle the request (get sqs-helloworld-length.external.metrics.k8s.io)"},{"type":"ScalingLimited","status":"True","lastTransitionTime":"2020-01-28T00:11:45Z","reason":"TooFewReplicas","message":"the
      desired replica count is increasing faster than the maximum scale rate"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"External","external":{"metricName":"sqs-helloworld-length","currentValue":"0"}}]'
    autoscaling.alpha.kubernetes.io/metrics: '[{"type":"External","external":{"metricName":"sqs-helloworld-length","targetValue":"30"}}]'
    kubectl.kubernetes.io/last-applied-configuration: |

**Comment by rubashanti** [comment]
Any help here ?

**Comment by chankh** [comment]
@rubashanti did you configure IRSA for the adapter with cloudwatch permissions? can you also paste the logs from the `k8s-cloudwatch-adapter` pod?

**Comment by rubashanti** [comment]
[adapter (1).log](https://github.com/awslabs/k8s-cloudwatch-adapter/files/4133442/adapter.1.log)

**Comment by rubashanti** [comment]
The cloudwatch permissions are correctly configured

**Comment by rubashanti** [comment]
kubectl get --raw "/apis/metrics.aws/v1alpha1/namespaces/default/externalmetrics/sqs-helloworld-length/" | jq
{
  "apiVersion": "metrics.aws/v1alpha1",
  "kind": "ExternalMetric",
  "metadata": {
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"metrics.aws/v1alpha1\",\"kind\":\"ExternalMetric\",\"metadata\":{\"annotations\":{},\"name\":\"sqs-helloworld-length\",\"namespace\":\"default\",\"region\":\"eu-east-2\"},\"spec\":{\"env\":[{\"name\":\"AWS_REGION\",\"value\":\"us-east-2\"},{\"name\":\"region\",\"value\":\"us-east-2\"}],\"name\":\"sqs-helloworld-length\",\"queries\":[{\"id\":\"sqs_helloworld_length\",\"metricStat\":{\"metric\":{\"dimensions\":[{\"name\":\"QueueName\",\"value\":\"helloworld\"},{\"name\":\"region\",\"value\":\"us-east-2\"},{\"name\":\"AWS_REGION\",\"value\":\"us-east-2\"}],\"metricName\":\"ApproximateNumberOfMessagesVisible\",\"namespace\":\"AWS/SQS\"},\"period\":300,\"stat\":\"Average\",\"unit\":\"Count\"},\"returnData\":true}],\"resource\":{\"resource\":\"deployment\"}}}\n"
    },
    "creationTimestamp": "2020-01-28T01:03:30Z",
    "generation": 1,
    "name": "sqs-helloworld-length",
    "namespace": "default",
    "resourceVersion": "29386",
    "selfLink": "/apis/metrics.aws/v1alpha1/namespaces/default/externalmetrics/sqs-helloworld-length",
    "uid": "ffd74dd7-4169-11ea-ac40-0a4f44cf89e4"
  },
  "spec": {
    "env": [
      {
        "name": "AWS_REGION",
        "value": "us-east-2"
      },
      {
        "name": "region",
        "value": "us-east-2"
      }
    ],
    "name": "sqs-helloworld-length",
    "queries": [
      {
        "id": "sqs_helloworld_length",
        "metricStat": {
          "metric": {
            "dimensions": [
              {
                "name": "QueueName",
                "value": "helloworld"
              },
              {
                "name": "region",
                "value": "us-east-2"
              },
              {
                "name": "AWS_REGION",
                "value": "us-east-2"
              }
            ],
            "metricName": "ApproximateNumberOfMessagesVisible",
            "namespace": "AWS/SQS"
          },
          "period": 300,
          "stat": "Average",
          "unit": "Count"
        },
        "returnData": true
      }
    ],
    "resource": {
      "resource": "deployment"
    }
  }
}

**Comment by chankh** [comment]
you have to add the `AWS_REGION` as an environment variable to the pod deployment, not under the `ExternalMetric`, so it should look something like this

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-cloudwatch-adapter
  name: k8s-cloudwatch-adapter
  namespace: custom-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-cloudwatch-adapter
  template:
    metadata:
      labels:
        app: k8s-cloudwatch-adapter
      name: k8s-cloudwatch-adapter
    spec:
      serviceAccountName: k8s-cloudwatch-adapter
      containers:
      - name: k8s-cloudwatch-adapter
        image: chankh/k8s-cloudwatch-adapter:v0.8.0
        args:
        - /adapter
        - --cert-dir=/tmp
        - --secure-port=6443
        - --logtostderr=true
        - --v=10
        env:
        - name: AWS_REGION
          value: us-west-2
        ports:
        - containerPort: 6443
          name: https
        - containerPort: 8080
          name: http
        volumeMounts:
        - mountPath: /tmp
          name: temp-vol
      volumes:
      - name: temp-vol
        emptyDir: {}
```
