### ISSUE TITLE
From time to time metrics will be exposed with a different type

### ISSUE THREAD

**Issue by z0lope0z** [awslabs/k8s-cloudwatch-adapter#37]
Hello,

I get this weird value from time to time for the result of my external metric. This is supposed to be a metric of type "Count" but for some reason the adapter thinks it's type "m".

Is there a way for me to test/see how the adapter reads the metric from cloudwatch? I'm not sure where these values come from

I'm expecting the result to come out like this:
```
mock-external-metric-hpa   Deployment/sqs-consumer   120/100 (avg)   1         5         4          8s
```

But from time to time the hpa reads values like this:
```
mock-external-metric-hpa   Deployment/sqs-consumer   92750m/100 (avg)   1         5         4          8s
```

external metric object
```
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: mock-queuesize-length
spec:
  name: mock-queuesize-length
  resource:
    resource: "deployment"
  queries:
    - id: mock_queuesize_length
      metricStat:
        metric:
          namespace: "CoolApp"
          metricName: "mockQueueName"
          dimensions:
            - name: QueueName2
              value: "helloworld"
        period: 300
        stat: Average
        unit: Count
      returnData: true
```

hpa
```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: mock-external-metric-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: sqs-consumer
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: External
    external:
      metricName: mock-queuesize-length
      targetAverageValue: 100
```
