### ISSUE TITLE
Get cloudwatch metrics in another AWS account?

### ISSUE THREAD

**Issue by johnjeffers** [awslabs/k8s-cloudwatch-adapter#4]
Is it possible to use this adapter to pull in cloudwatch metrics from another AWS account?

**Comment by johnjeffers** [comment]
Never mind, figured out you can easily do this by passing env vars to the Deployment with an access key/secret key. Leaving this in case it's helpful for someone else in the future.

```
spec:
  template:
    spec:
      containers:
      - name: k8s-cloudwatch-adapter
        ...
        env:
        - name: AWS_ACCESS_KEY_ID
          value: <the-key>
        - name: AWS_SECRET_ACCESS_KEY
          value: <the-secret>
```
