### ISSUE TITLE
The parameter MetricDataQueries is required

### ISSUE THREAD

**Issue by lemasson-h** [awslabs/k8s-cloudwatch-adapter#5]
Hi,

I have been following the post here: https://aws.amazon.com/blogs/compute/scaling-kubernetes-deployments-with-amazon-cloudwatch-metrics/ to try to autoscale based on a queue in sqs.

I have applied exactly the elements in this file: https://raw.githubusercontent.com/awslabs/k8s-cloudwatch-adapter/master/deploy/adapter.yaml (exactly as they are defined) in my cluster.

I then applied the metric definition:
```yaml
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: sqs-my-list-of-elements-queue-length
  namespace: unicorn
spec:
  name: sqs-my-list-of-elements-queue-length
  resource:
    resource: "deployment"
    queries:
      - id: sqs_my_list_of_elements_queue_length
        expression:
        metricStat:
          metric:
            namespace: "AWS/SQS"
            metricName: "ApproximateNumberOfMessagesVisible"
            dimensions:
              - name: QueueName
                value: "my-list-of-elements"
          period: 300
          stat: Average
          unit: Count
        returnData: true
```

Then the autoscaling element:
```yaml
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: my-worker-listening-to-my-queue-scaler
  namespace: unicorn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-worker-listening-to-my-queue
  minReplicas: 5
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metricName: sqs-my-list-of-elements-queue-length
      targetValue: 5
```

The only 2 differences with the original configuration are:
-  my metric & autoscaling are in a specific namespace
- the value of spec.scaleTargetRef.apiVersion was apps/v1beta1, but as I was using the deployment of the apiVersion apps/v1 for "my-worker-listening-to-my-queue", so I changed it.

The problem is that I am getting those errors from the autoscaling when I check why it's not autoscaling:
```bash
$kubectl describe hpa my-worker-listening-to-my-queue-scaler --namespace unicorn

Name:                                                              my-worker-listening-to-my-queue-scaler
Namespace:                                                         unicorn
Labels:                                                            <none>
Annotations:                                                       kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"my-worker-listening-to-my-queue-scaler","namespace...
CreationTimestamp:                                                 Fri, 05 Jul 2019 14:50:37 +0100
Reference:                                                         Deployment/my-worker-listening-to-my-queue
Metrics:                                                           ( current / target )
  "sqs-my-list-of-elements-queue-length" (target value):  <unknown> / 5
Min replicas:                                                      5
Max replicas:                                                      10
Deployment pods:                                                   5 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric unicorn/sqs-my-list-of-elements-queue-length/nil: unable to fetch metrics from external metrics API: ValidationError: The parameter MetricDataQueries is required.

  status code: 400, request id: xxx
```

I tried to see if I could get more information from the pod log in the custom-metrics namespace, but it didn't seem so:
```
 1 round_trippers.go:447]     Date: Fri, 05 Jul 2019 13:51:37 GMT
I0705 13:51:37.407653       1 request.go:942] Response Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"resourceAttributes":{"namespace":"unicorn","verb":"list","group":"external.metrics.k8s.io","version":"v1beta1","resource":"sqs-my-list-of-elements-queue-length"},"user":"system:serviceaccount:kube-system:horizontal-pod-autoscaler","group":["system:serviceaccounts","system:serviceaccounts:kube-system","system:authenticated"]},"status":{"allowed":true,"reason":"RBAC: allowed by ClusterRoleBinding \"k8s-cloudwatch-adapter:external-metrics-reader\" of ClusterRole \"k8s-cloudwatch-adapter:external-metrics-reader\" to ServiceAccount \"horizontal-pod-autoscaler/kube-system\""}}
I0705 13:51:37.407729       1 handler.go:143] cloudwatch-metrics-adapter: GET "/apis/external.metrics.k8s.io/v1beta1/namespaces/unicorn/sqs-my-list-of-elements-queue-length" satisfied by gorestful with webservice /apis/external.metrics.k8s.io/v1beta1
I0705 13:51:37.407763       1 provider_external.go:17] Received request for namespace: unicorn, metric name: sqs-my-list-of-elements-queue-length, metric selectors: 
E0705 13:51:37.435663       1 client.go:98] err: ValidationError: The parameter MetricDataQueries is required.

	status code: 400, request id: xxx
E0705 13:51:37.435684       1 provider_external.go:31] bad request: ValidationError: The parameter MetricDataQueries is required.
```

I am not sure if I made a mistake or if it's something else, would you be able to help me, please?

Thank you,

**Comment by chankh** [comment]
@lemasson-h it looks like your metric definition yaml is slightly off, if you look at the sample provided, your `queries` line has additional indent, which shift it out of place, and that's why it is not able to pick up the MetricDataQueries

```
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: sqs-my-list-of-elements-queue-length
  namespace: unicorn
spec:
  name: sqs-my-list-of-elements-queue-length
  resource:
    resource: "deployment"
  queries:
    - id: sqs_my_list_of_elements_queue_length
      metricStat:
        metric:
          namespace: "AWS/SQS"
          metricName: "ApproximateNumberOfMessagesVisible"
          dimensions:
            - name: QueueName
              value: "my-list-of-elements"
        period: 300
        stat: Average
        unit: Count
      returnData: true
```
