### ISSUE TITLE
The current value is always 0

### ISSUE THREAD

**Issue by sangreal** [awslabs/k8s-cloudwatch-adapter#51]
I setup the SQS based externalmetrics but No metrics coming in even there is no error in the HPA description or the `cloudwatch-adapter`. Have done tons of tempts of changing still no clues. 

externalmetrics
---
```
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: push-ml-coordinator-queue-dev
  namespace: sn-push
spec:
  name: push-ml-coordinator-queue-dev
  queries:
    - id: sqs_sn_push_ml_coordinator_queue_dev
      metricStat:
        metric:
          dimensions:
            - name: QueueName
              value: "sn_push_user_incoming_queue_dev"
          metricName: "ApproximateNumberOfMessagesVisible"
          namespace: "AWS/SQS"
        period: 60
        stat: Average
        unit: Count
      returnData: true
  resource:
    resource: "deployment"
```
---
HPA
---
```
Labels:                                                    <none>
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: coordinator-hpa
  namespace: sn-push
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sn-push-ml-coordinator
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: External
    external:
      metricName: push-ml-coordinator-queue-dev
      targetAverageValue: 10
```
---
HPA Description
---
```
Name:                                                      coordinator-hpa
Namespace:                                                 sn-push
Labels:                                                    <none>
Annotations:                                               <none>
CreationTimestamp:                                         Fri, 11 Sep 2020 12:02:21 +0800
Reference:                                                 Deployment/sn-push-ml-coordinator
Metrics:                                                   ( current / target )
  "push-ml-coordinator-queue-dev" (target average value):  0 / 10
Min replicas:                                              1
Max replicas:                                              4
Deployment pods:                                           1 current / 1 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from external metric push-ml-coordinator-queue-dev(nil)
  ScalingLimited  True    TooFewReplicas    the desired replica count is less than the minimum replica count
```
---

Cloudwatch Adapter logs snippet
---
```
I0911 05:57:25.228094       1 handler.go:69] externalMetricInfo: &{{ } {push-ml-coordinator-queue-dev  sn-push /apis/metrics.aws/v1alpha1/namespaces/sn-push/externalmetrics/push-ml-coordinator-queue-dev fa008218-8423-41bd-a535-6168223aad9a 165916796 1 2020-09-11 04:01:27 +0000 UTC <nil> <nil> map[] map[] [] []  []} {push-ml-coordinator-queue-dev [{  sqs_sn_push_ml_coordinator_queue_dev  {{[{QueueName sn_push_user_incoming_queue_dev}] NumberOfEmptyReceives AWS/SQS} 60 Average Count} true}]}}
I0911 05:57:25.228226       1 handler.go:114] adding to cache item 'push-ml-coordinator-queue-dev' in namespace 'sn-push'
I0911 05:57:25.228230       1 controller.go:122] successfully processed item '{sn-push/push-ml-coordinator-queue-dev ExternalMetric}'
```
---

If you need any further information. Please do let me know.
