### ISSUE TITLE
SQS Metrics Appear to be Multiplied by 1000

### ISSUE THREAD

**Issue by stevenpall** [awslabs/k8s-cloudwatch-adapter#6]
Hi there,

I'm trying to use the `ApproximateNumberOfMessagesVisible` metric from an SQS queue, and for some reason the current value is being reported as the actual number * 1000. As a workaround, I've just multiplied the target value by 1000 as well, but this is unintuitive.

For reference, here are my `ExternalMetric` and `HorizontalPodAutoscaler` objects:
```
apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: test-sqs-length
spec:
  name: test-sqs-length
  resource:
    resource: "deployment"
  queries:
    - id: sqs_test_length
      metricStat:
        metric:
          namespace: "AWS/SQS"
          metricName: "ApproximateNumberOfMessagesVisible"
          dimensions:
            - name: QueueName
              value: "test"
        period: 300
        stat: Average
        unit: Count
      returnData: true
```
```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: test
  minReplicas: 2
  maxReplicas: 50
  metrics:
  - type: External
    external:
      metricName: test-sqs-length
      targetValue: 1000000
```
In this case, I'm actually aiming for a `targetValue` of 1000. I'm not sure if this is a bug or something I'm doing wrong, but I'd appreciate some assistance either way!
