### ISSUE TITLE
SQS ExternalMetric HPA error

### ISSUE THREAD

**Issue by rangarb885** [awslabs/k8s-cloudwatch-adapter#91]
In my environment, I hav AWS EKS - 1.16 with metric server v0.5.0 and hpa. I have installed this v0.10.0 Cloudwatch adapter to the cluster under namespace _custom-metrics_

`kubectl get --raw "/apis/external.metrics.k8s.io" | jq .`
```
{
  "kind": "APIGroup",
  "apiVersion": "v1",
  "name": "external.metrics.k8s.io",
  "versions": [
    {
      "groupVersion": "external.metrics.k8s.io/v1beta1",
      "version": "v1beta1"
    }
  ],
  "preferredVersion": {
    "groupVersion": "external.metrics.k8s.io/v1beta1",
    "version": "v1beta1"
  }
}
```

I have attached IAM Role to the service-account as below:

```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: k8s-cloudwatch-adapter
  namespace: custom-metrics
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT>:role/myrole
```

Here `myrole` has `AssumeRoleWithWebIdentity`for the OIDC with sub as `system:serviceaccount:custom-metrics:k8s-cloudwatch-adapter` 

While i try to follow the steps as on [scaling-kubernetes-deployments-with-amazon-cloudwatch-metrics](https://aws.amazon.com/blogs/compute/scaling-kubernetes-deployments-with-amazon-cloudwatch-metrics/), 
the HPA shows the below error and scaling does not happen.

```
ScalingActive  False   FailedGetExternalMetric  the HPA was unable to compute the replica count: unable to get external metric perf/hello-queue-length/nil: unable to fetch metrics from external metrics API: no metric query found                
```

I see the below message on adapter logs

`1 metric_cache.go:44] metric not found ExternalMetric/perf/hello-queue-length` 

Both HPA (sqs-consumer-scaler) and ExternalMetric (sqs-helloworld-length) are installed on the same namespace as app. Here in this case *perf*

What would be the reason for this failure?
